name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: header,community,repositories,metadata
          plugin_habits: true
          plugin_wakatime: true
          plugin_wakatime_sections: time,languages-graph,editors-graph
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
